src/tanaka_kento/beans/UserPost.java
package tanaka_kento.beans;

import java.io.Serializable;
import java.util.Date;

public class UserPost implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
	private String account;
    private String name;
    private int userId;
    private String subject;
    private String text;
    private String category;
    private int delFrag;
    public int getDelFrag() {
		return delFrag;
	}
	public void setDelFrag(int delFrag) {
		this.delFrag = delFrag;
	}
	private Date createdDate;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getText() {
		return text;
	}
	public String[] getSplitedText() {
        return text.split("\n");
    }
	public void setText(String text) {
		this.text = text;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}

src/tanaka_kento/controller/LoginServlet.java
package tanaka_kento.controller;


import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import tanaka_kento.beans.BPInfo;
import tanaka_kento.beans.User;
import tanaka_kento.service.BPInfoService;
import tanaka_kento.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        String account = request.getParameter("account");
        String password = request.getParameter("password");

        LoginService loginService = new LoginService();
        User user = loginService.login(account, password);


        List<String> messages = new ArrayList<String>();
        HttpSession session = request.getSession();
        if (user != null) {
        	int banFrag = user.getBan();
        	if (banFrag == 1) {
                messages.add("アカウントが停止しています");
                session.setAttribute("errorMessages", messages);
                request.getRequestDispatcher("login.jsp").forward(request, response);
            }
        	List<BPInfo> bInfos = new BPInfoService().getBInfo();
	        session.setAttribute("bInfos", bInfos);
            session.setAttribute("loginUser", user);
            response.sendRedirect("./");
        } else if (user == null){
        	messages.add("ログインできませんでした");
        	session.setAttribute("errorMessages", messages);
        	request.getRequestDispatcher("login.jsp").forward(request, response);
        }



    }

}

src/tanaka_kento/controller/ManegementServlet.java
package tanaka_kento.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import tanaka_kento.beans.UserInfo;
import tanaka_kento.service.ManegementService;

@WebServlet(urlPatterns = { "/manegement"})
public class ManegementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException  {
		List<UserInfo> userInfo = new ManegementService().getUserInfo();
		request.setAttribute("infos", userInfo);
		request.getRequestDispatcher("manegement.jsp").forward(request, response);
	}



}

src/tanaka_kento/controller/PostServlet.java
package tanaka_kento.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import tanaka_kento.beans.Post;
import tanaka_kento.beans.User;
import tanaka_kento.service.PostService;

@WebServlet(urlPatterns = { "/newPost" })
public class PostServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("post.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		HttpSession session = request.getSession();

		List<String> posts = new ArrayList<String>();

		if (isValid(request, posts) == true) {

			User user = (User) session.getAttribute("loginUser");

			Post post = new Post();
			post.setSubject(request.getParameter("subject"));
			post.setCategory(request.getParameter("category"));
			post.setText(request.getParameter("text"));
			post.setUserId(user.getId());

			new PostService().register(post);
			post.setId(post.getId());

			response.sendRedirect("./");
		} else {
			session.setAttribute("errorMessages", posts);
			response.sendRedirect("newPost");
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> posts) {
		String text = request.getParameter("text");
		String subject = request.getParameter("subject");
		String category = request.getParameter("category");
		if (StringUtils.isEmpty(text) == true) {
			posts.add("本文を入力してください");
		}
		if (1000 < text.length()) {
			posts.add("1000文字以下で入力してください");
		}
		if (StringUtils.isEmpty(subject) == true) {
			posts.add("件名を入力してください");
		}
		if (30 < subject.length()) {
			posts.add("30文字以下で入力してください");
		}
		if (StringUtils.isEmpty(category) == true) {
			posts.add("カテゴリーを入力してください");
		}
		if (10 < category.length()) {
			posts.add("10文字以下で入力してください");
		}
		if (posts.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}

src/tanaka_kento/controller/SettingsServlet.java
package tanaka_kento.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import tanaka_kento.beans.User;
import tanaka_kento.beans.UserInfo;
import tanaka_kento.exception.NoRowsUpdatedRuntimeException;
import tanaka_kento.service.UserService;

@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

    	HttpSession session = request.getSession();
    	UserInfo  editUser;
    	if(request.getParameter("id") != null) {
        editUser = new UserService().getUser(Integer.parseInt(request.getParameter("id")));
    	} else {
    		editUser = (UserInfo) session.getAttribute("editUser");

    	}
        if(editUser != null) {
        	request.setAttribute("editUser", editUser);
	        request.getRequestDispatcher("settings.jsp").forward(request, response);
        } else {
        	response.sendRedirect("manegement");
        }
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

        List<String> errors = new ArrayList<String>();
        HttpSession session = request.getSession();
        User user = (User) request.getSession().getAttribute("loginUser");

        UserInfo editUser = getEditUser(request);

    	if (isValid(request, errors) == true) {
            try {
            	int keep = 0;
            	if(request.getParameter("password") == "") {
            		keep = 1;
            	}
                new UserService().update(editUser, keep);
            } catch (NoRowsUpdatedRuntimeException e) {
            	errors.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
                session.setAttribute("errorMessages", errors);
                request.setAttribute("editUser", editUser);
                request.getRequestDispatcher("settings.jsp").forward(request, response);
                return;
            }
            session.setAttribute("editUser", editUser);
            int editId = editUser.getId();
            int loginId = user.getId();
            if (editId == loginId) {
            	user.setAccount(editUser.getAccount());
            	user.setName(editUser.getName());
            	user.setBan(editUser.getBanFrag());
            	user.setBranch(editUser.getBranch());
            	user.setPosition(editUser.getPosition());
            	session.setAttribute("loginUser", user);
            }
            response.sendRedirect("manegement");
    	} else {
        	session.setAttribute("errorMessages", errors);
			response.sendRedirect("settings");
        }
        }


    private UserInfo getEditUser(HttpServletRequest request)
            throws IOException, ServletException {

        UserInfo editUser = new UserInfo();
        editUser.setName(request.getParameter("name"));
        editUser.setAccount(request.getParameter("account"));
        if(request.getParameter("password") != "") {
        	editUser.setPassword(request.getParameter("password"));
        }
        editUser.setId(Integer.parseInt(request.getParameter("id")));
        editUser.setBranch(Integer.parseInt(request.getParameter("branch")));
        editUser.setPosition(Integer.parseInt(request.getParameter("position")));
        return editUser;
    }
    private boolean isValid(HttpServletRequest request, List<String> errors) {
    	HttpSession session = request.getSession();
    	UserInfo  editUser;
    	if(request.getParameter("id") != null) {
        editUser = new UserService().getUser(Integer.parseInt(request.getParameter("id")));
    	} else {
    		editUser = (UserInfo) session.getAttribute("editUser");
    	}
		int editId = Integer.parseInt(request.getParameter("id"));
		int editedId = editUser.getId();
		String account = request.getParameter("account");
		 List<User> checkId = new UserService().getAccount();
		 String name = request.getParameter("name");
		 String pass = request.getParameter("password");
		 String pass2 = request.getParameter("password2");
		 int branch = Integer.parseInt(request.getParameter("branch"));
		 int position = Integer.parseInt(request.getParameter("position"));
		 if (!( 0 < branch && branch < 7) || !(0 < position && position < 5)) {
			 errors.add("支店か役職が入力されていません");
		 }
		 if ((branch == 1 && position == 3) || (branch == 1 && position == 4) || (!(branch == 1) && position == 1) || (!(branch == 1) && position == 2)) {
			 errors.add("支店と役職の組み合わせが不正です");
		 }
		 if (name.length() == 0) {
			 errors.add("名前を入力してください");
		 }
		 if (name.length() > 10) {
			 errors.add("名前は10文字以下でお願いします");
		 }
		 if(account.length() < 6 || 20 < account.length()) {
			 errors.add("ログインIDは6文字以上20文字以下でお願いします");
		 }
		 if(!pass.equals(pass2)) {
			 errors.add("パスワードが一致しません");
		 }
		 if(pass != "") {
			 if(pass.length() < 6 || 20 < pass.length()) {
				 errors.add("パスワードは6文字以上20文字以下でお願いします");
			 }
		 }
		 if (editId != editedId) {
			 for (int i = 0; i < checkId.size(); i++) {
				 String a = checkId.get(i).getAccount();
				 if (account.equals(a)) {
					 errors.add("このログインIDは利用できません");
				 }
			 }
		 }
		 if (errors.size() == 0) {
				return true;
			} else {
				return false;
			}
	}


}

src/tanaka_kento/controller/SignUpServlet.java
package tanaka_kento.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import tanaka_kento.beans.User;
import tanaka_kento.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {


        HttpSession session = request.getSession();
        List<String> errors = new ArrayList<String>();

        if (isValid(request, errors) == true) {
            User user = new User();
            user.setName(request.getParameter("name"));
            user.setAccount(request.getParameter("account"));
            user.setPassword(request.getParameter("password"));
            user.setBranch(Integer.parseInt(request.getParameter("branch")));
            user.setPosition(Integer.parseInt(request.getParameter("position")));
            new UserService().register(user);

            session.setAttribute("signupUser", user);

            response.sendRedirect("manegement");
        } else {
        	session.setAttribute("errorMessages", errors);
			response.sendRedirect("signup");
        }

    }

    private boolean isValid(HttpServletRequest request, List<String> errors) {
		String editId = request.getParameter("account");
		 List<User> checkId = new UserService().getAccount();
		 String name = request.getParameter("name");
		 String pass = request.getParameter("password");
		 String pass2 = request.getParameter("password2");
		 int branch = Integer.parseInt(request.getParameter("branch"));
		 int position = Integer.parseInt(request.getParameter("position"));
		 if (!( 0 < branch && branch < 7) || !(0 < position && position < 5)) {
			 errors.add("支店か役職が入力されていません");
		 }
		 if ((branch == 1 && position == 3) || (branch == 1 && position == 4) || (!(branch == 1) && position == 1) || (!(branch == 1) && position == 2)) {
			 errors.add("支店と役職の組み合わせが不正です");
		 }
		 if (name.length() == 0) {
			 errors.add("名前を入力してください");
		 }
		 if (name.length() > 10) {
			 errors.add("名前は10文字以下でお願いします");
		 }
		 if(editId.length() < 6 || 20 < editId.length()) {
			 errors.add("ログインIDは6文字以上20文字以下でお願いします");
		 }
		 if(pass.length() < 6 || 20 < pass.length()) {
			 errors.add("パスワードは6文字以上20文字以下でお願いします");
		 }
		 if(!pass.equals(pass2)) {
			 errors.add("パスワードが一致しません");
		 }
		 for (int i = 0; i < checkId.size(); i++) {
			 String a = checkId.get(i).getAccount();
			 if (editId.equals(a)) {
				 errors.add("このログインIDは利用できません");
			 }
		 }
		 if (errors.size() == 0) {
				return true;
			} else {
				return false;
			}
	}

}

src/tanaka_kento/controller/TopServlet.java
package tanaka_kento.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import tanaka_kento.beans.User;
import tanaka_kento.beans.UserComment;
import tanaka_kento.beans.UserPost;
import tanaka_kento.service.CommentService;
import tanaka_kento.service.PostService;

@WebServlet(urlPatterns = { "/index.jsp"})
public class TopServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		 User user = (User) request.getSession().getAttribute("loginUser");
	     if (user != null) {
	    	 List<UserPost> posts = new PostService().getPost();

		     request.setAttribute("posts", posts);
	     }

	     List<UserComment> comments = new CommentService().getComment();

	     request.setAttribute("comments", comments);
	     request.getRequestDispatcher("top.jsp").forward(request, response);;
	}

}

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="./js/jquery-3.4.1.js"></script>
		<script type="text/javascript" src="./js/test.js"></script>
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <form action="login" method="post" class="_form">
            	<br />
                <label for="account">ログインID</label>
                <input name="account" class="field1" id="account" placeholder="ログインIDを入力してください"/>
                <br />
                <label for="password">パスワード</label>
                <input name="password" class="field2" type="password" id="password" placeholder="パスワードを入力してください"/>
                <br />
                <input type="submit" value="ログイン" />
                <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright">TanakaKento</div>

        </div>
    </body>
</html>

WebContent/manegement.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<style>
.table1 {
  border: 1px solid gray;
}
.table1 th, .table1 td {
  border: 1px solid gray;
}
</style>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${loginUser.account}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
		<script type="text/javascript" src="./js/jquery-3.4.1.js"></script>
    	<script type="text/javascript" src="./js/test.js"></script>
    </head>
    <body>IDをクリックするとユーザーを編集できます
    	<form action="manegement" method="get">
    		<br />
    		<table class="table1">
    			<tr>
    				<th>ID</th>
    				<th>ログインID</th>
    				<th>名前</th>
    				<th>所属</th>
    				<th>役職</th>
    				<th>状態</th>
    			</tr>
    			<c:forEach items="${infos}" var="info">
    				<tr>
    					<td><a href="settings?id=${info.id}">${info.id}</a></td>
    					<td>${info.account}</td>
    					<td>${info.name}</td>
    					<td>${info.branchName}</td>
    					<td>${info.positionName}</td>
    					<td>
    						<form action="userBan" method="post">
    							<input type="hidden" name="id" value="${info.id}">
    							<c:if test="${info.id != loginUser.id}">
    								<c:if test="${info.banFrag == 0}">稼働中
										<input type="hidden" name="frag" value="1">
										<input type="submit" value="停止" class="exe">
									</c:if>
									<c:if test="${info.banFrag == 1}">停止中
										<input type="hidden" name="frag" value="0">
										<input type="submit" value="復活" class="exe">
									</c:if>
								</c:if>
								<c:if test="${info.id == loginUser.id}">
									ログイン中
								</c:if>
							</form>
    					</td>
    				</tr>
    			</c:forEach>
    		</table>
    	</form>


    	<a href="signup">新規登録</a>
    	<a href="./">戻る</a>

</body>
</html>

WebContent/post.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>新規投稿</title>
    <link href="css/style.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="./js/jquery-3.4.1.js"></script>
    <script type="text/javascript" src="./js/test.js"></script>
    </head>
    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages}">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>

            <form action="newPost" method="post" name="form1" class="_form" id="postForm">
	            <br />
	            <label for="subject">件名</label>
	            <input class="field" name="subject" id="subject"  placeholder="(30文字)" />
	            <small id="errorS"></small>
	            <br />
	            <label for="category">カテゴリー</label>
	            <input class="field" name="category" id="category"  placeholder="(10文字)" />
	            <small id="errorC"></small>
	            <br />
	            <label for="text">本文</label>
	            <textarea class="field" name="text" cols="50" rows="25" id="post"  placeholder="(1000文字)" ></textarea>
	            <small id="errorP"></small>
	            <br />
	            <input type="submit" value="投稿" id="go" class="sub"/>
	            <br />
	            <a href="./">戻る</a>
            </form>

            <div class="copyright" id="hoge">Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/top.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>掲示板</title>
<link href="css/style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="./js/jquery-3.4.1.js"></script>
<script type="text/javascript" src="./js/test.js"></script>

</head>
<body>
	<c:if test="${ not empty errorMessages }">
     	<div class="errorMessages">
       		<ul>
     			<c:forEach items="${errorMessages}" var="message">
         			<li><c:out value="${message}" />
           		</c:forEach>
   			</ul>
 		</div>
        <c:remove var="errorMessages" scope="session"/>
     </c:if>
	<div class="header">
		<c:if test="${not empty loginUser}">
			<a href="logout">ログアウト</a>
			<select name="select" onChange="location.href=value;">
				<option value="#">メニュー</option>
				<option value="newPost">新規投稿</option>
				<c:if test="${loginUser.position == 1}">
					<option value="manegement">ユーザー管理</option>
				</c:if>
			</select>

	<div class="search">
		<form action="search" method="get" >
			<label for="key" >カテゴリーのキーワードで検索します</label> <input name="key" id="key" value="${key}"  placeholder="カテゴリー検索(10文字)"/><br>
			<ul id="errorsK"></ul>
			<input type="date" name="date1" id="date1" value="${date1}"/>
			<c:out value="～"></c:out>
			<input type="date" name="date1" id="date2" value="${date2}"/>
			<ul id="errorsD"></ul>
			<input type="submit"  value="検索" id="sort"/>
		</form>

	</div>
	</c:if></div>
	<div class="messages">
		<c:forEach items="${posts}" var="post">
			<c:if test="${post.delFrag == 0}">
				<div class="message">
					<div class="account-name">
						<br /> <span class="account"><c:out
								value="${post.account}" /></span> <span class="name"><c:out
								value="${post.name}" /></span>
					</div>
					<div class="subject">
						件名：
						<c:out value="${post.subject}" />
					</div>
					<div class="category">
						カテゴリー：
						<c:out value="${post.category}" />
					</div>
					<div class="text">
						本文:<br>
						<c:forEach var="line" items="${post.splitedText}">
    						<c:out value="${line}"/><br/>
    					</c:forEach>
					</div>
					<div class="date">
						<fmt:formatDate value="${post.createdDate}"
							pattern="yyyy/MM/dd HH:mm:ss" />

						<c:if test="${post.userId == loginUser.id}">
							<form action="postDel" method="post">
								<input type="hidden" value="${post.id}" name="postId">
								<input type="submit" value="削除" class="exe">

							</form>
						</c:if>
					</div>
				</div>
				<div class="form-area">
					<form action="Comment" method="post">
						コメント<br />
						<input type="hidden" name="postId" value="${post.id}">
						<textarea name="comment" cols="50" rows="5"
						 class="comment_box"  placeholder="(500文字)"></textarea>
						 <p id="inputLength">0文字</p>
						 <ul class="errors"></ul>
						<input type="submit" value="送信" class="commentSubmit" >
					</form>
				</div>
				<div class="comment">

					<c:forEach items="${comments}" var="comment">
						<c:if test="${post.id == comment.postId}">
						<c:if test="${comment.delFrag == 0}">
							<div class="comment">
								<div class="account-name">
									<span class="account"><c:out value="${comment.account}" /></span>
									<span class="name"><c:out value="${comment.name}" /></span>
								</div>
								<div class="text">
									<c:forEach items="${comment.splitedText}" var="line">
										<c:out value="${line}" /><br>
									</c:forEach>
								</div>
								<div class="date">
									<fmt:formatDate value="${comment.createdDate}"
										pattern="yyyy/MM/dd HH:mm:ss" />
										<c:if test="${comment.userId == loginUser.id}">
							<form action="commentDel" method="post">
								<input type="hidden" value="${comment.id}" name="commentId"> <input
									type="submit" value="削除" class="exe">

							</form>
						</c:if>
								</div>
							</div>
						</c:if>
						</c:if>
					</c:forEach>

				</div>
			</c:if>

		</c:forEach>

	</div>

	<div class="copyright">TanakaKento</div>
</body>
</html>